# Generated by Django 5.0.2 on 2024-05-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=60)),
                ('relationship', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
