# Generated by Django 5.0.2 on 2024-05-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_icons', models.CharField(max_length=50)),
                ('depart_title', models.CharField(max_length=50)),
                ('depart_desc', models.TextField()),
            ],
        ),
    ]
